import{useCallback,useEffect,useMemo,useRef,useState}from"react";import{Activity,Archive,ArrowUp,BrainCircuit,Check,ChevronRight,Clock3,FileText,Home,MoreHorizontal,Paperclip,Pause,Play,Settings,Sparkles,Square,Terminal,Wifi}from"lucide-react";import type{AgentEvent,AgentState,Task}from"@abhi/types";import{Office}from"./Office";
const API="/api";
const initialTasks:Task[]=[];
function App(){const[input,setInput]=useState("");const[tasks,setTasks]=useState<Task[]>(initialTasks);const[state,setState]=useState<AgentState>("IDLE");const[status,setStatus]=useState("Ready for the next job.");const[active,setActive]=useState("office");const[stream,setStream]=useState("");const[inputRef]=useState(()=>({current:null as HTMLTextAreaElement|null}));const current=tasks.find(t=>!["COMPLETED","FAILED","CANCELLED"].includes(t.status))??tasks[0];
const refresh=useCallback(()=>fetch(`${API}/tasks`).then(r=>r.json()).then(setTasks).catch(()=>{}),[]);
useEffect(()=>{refresh();fetch(`${API}/agent/status`).then(r=>r.json()).then(s=>{setState(s.state);setStatus(s.text)}).catch(()=>{});const es=new EventSource(`${API}/events`);es.onmessage=e=>{const ev:AgentEvent=JSON.parse(e.data);if(ev.type==="agent.status"){setState(ev.payload.state as AgentState);setStatus(String(ev.payload.text))}if(ev.type==="message.delta")setStream(x=>x+String(ev.payload.text??""));if(ev.type.startsWith("task.")){refresh();if(ev.type==="task.completed")setStream("")}};return()=>es.close()},[refresh]);
async function submit(){const description=input.trim();if(!description)return;setInput("");setStream("");await fetch(`${API}/tasks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description})});refresh()}
async function action(name:string){if(!current)return;await fetch(`${API}/tasks/${current.id}/${name}`,{method:"POST"});refresh()}
const title=useMemo(()=>state==="IDLE"?"Hey. What are we working on?":status,[state,status]);
return <div className="app-shell"><aside className="rail"><div className="brand"><div className="brand-mark">A<span/></div><b>ABHI</b></div><nav aria-label="Main navigation">{[["office",Home,"Office"],["activity",Activity,"Activity"],["tasks",Archive,"Tasks"],["memory",BrainCircuit,"Memory"],["files",FileText,"Files"]].map(([id,Icon,label]:any)=><button key={id} onClick={()=>setActive(id)} className={active===id?"active":""} aria-label={label}><Icon size={19}/><span>{label}</span></button>)}</nav><button className="settings" onClick={()=>setActive("settings")}><Settings size={19}/><span>Settings</span></button></aside>
<main><header><div className="mobile-brand"><div className="brand-mark">A<span/></div><b>ABHI</b></div><div className="room-title"><span>ABHI /</span> OFFICE <i>PRIVATE</i></div><div className="online"><i/><div><b>ABHI</b><span><Wifi size={11}/> ONLINE</span></div><button aria-label="More options"><MoreHorizontal size={20}/></button></div></header>
<div className="workspace">{active==="office"?<><section className="office-wrap"><div className="scene-label"><span>01</span><div><b>THE OFFICE</b><small>PERSONAL WORKSPACE</small></div></div><Office state={state} onObject={setActive}/><div className="state-card"><div className={`state-orb ${state.toLowerCase()}`}><Sparkles size={17}/></div><div><small>{state}</small><b>{title}</b></div><span className="live-pill"><i/> LIVE</span></div></section><ActivityPanel task={current} state={state} stream={stream} onAction={action}/></>:<SectionView section={active} tasks={tasks} onBack={()=>setActive("office")}/>}</div>
<div className="composer"><div className="prompt"><button aria-label="Attach file"><Paperclip size={18}/></button><textarea ref={e=>{inputRef.current=e}} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}}} placeholder="Give ABHI a job…" rows={1}/><span className="mode"><Sparkles size={13}/> AGENT</span><button className="send" onClick={submit} aria-label="Send task"><ArrowUp size={18}/></button></div><div className="composer-foot"><span>ABHI can use tools and may ask for approval.</span><span><kbd>↵</kbd> send · <kbd>⇧↵</kbd> new line</span></div></div></main></div>}
function ActivityPanel({task,state,stream,onAction}:{task?:Task,state:AgentState,stream:string,onAction:(s:string)=>void}){return <aside className="activity-panel"><div className="panel-head"><div><small>CURRENT ACTIVITY</small><h2>{task?.status==="COMPLETED"?"Recently completed":"Agent workspace"}</h2></div><span className="count">{task?"01":"00"}</span></div>{task?<><div className="task-title"><span className="task-icon"><Terminal size={18}/></span><div><small>TASK {task.id.slice(0,5).toUpperCase()}</small><b>{task.title}</b></div></div><div className="progress-meta"><span>{task.currentActivity}</span><b>{task.progress}%</b></div><div className="progress"><i style={{width:`${task.progress}%`}}/></div><div className="steps">{task.steps.map(s=><div className={s.status} key={s.id}><i>{s.status==="done"?<Check size={12}/>:s.status==="active"?<span/>:null}</i><span>{s.safeSummary}</span></div>)}</div>{stream&&<div className="stream"><small>SIMULATED RESPONSE</small>{stream}</div>}<div className="task-actions">{task.status==="PAUSED"?<button onClick={()=>onAction("resume")}><Play size={14}/> Resume</button>:!(["COMPLETED","FAILED","CANCELLED"].includes(task.status))&&<button onClick={()=>onAction("pause")}><Pause size={14}/> Pause</button>} {!(["COMPLETED","FAILED","CANCELLED"].includes(task.status))&&<button onClick={()=>onAction("cancel")}><Square size={12}/> Stop</button>}</div></>:<div className="empty"><div className="radar"><i/><span/></div><b>Standing by</b><p>Give ABHI a job. Its plan and safe activity updates will appear here.</p></div>}<div className="panel-footer"><Clock3 size={14}/><span>{state==="IDLE"?"No active task":"Realtime connection active"}</span><i/></div></aside>}
function SectionView({section,tasks,onBack}:{section:string,tasks:Task[],onBack:()=>void}){const labels:any={activity:[Activity,"Live activity","Monitor what ABHI is doing without exposing private reasoning."],tasks:[Archive,"Tasks","Pause, resume, inspect, and manage autonomous work."],memory:[BrainCircuit,"Memory","Information is only saved under your configured memory rules."],files:[FileText,"Knowledge & files","Upload and attach secure context to future tasks."],settings:[Settings,"Settings","Control autonomy, models, tools, security, and notifications."],agent:[Sparkles,"ABHI","Your primary AI coworker is online."]};const [Icon,title,sub]=labels[section]??labels.activity;return <section className="section-view"><button className="back" onClick={onBack}>← Back to office</button><div className="section-hero"><div><Icon size={24}/></div><span><small>WORKSPACE</small><h1>{title}</h1><p>{sub}</p></span></div>{section==="tasks"||section==="activity"?<div className="task-grid">{tasks.length?tasks.map(t=><article key={t.id}><div className="task-row"><span className={`status-dot ${t.status.toLowerCase()}`}/><small>{t.status.replaceAll("_"," ")}</small><b>{t.progress}%</b></div><h3>{t.title}</h3><p>{t.currentActivity}</p><div className="mini-progress"><i style={{width:`${t.progress}%`}}/></div><button>Inspect task <ChevronRight size={14}/></button></article>):<div className="section-empty">No tasks yet. Return to the office and give ABHI a job.</div>}</div>:<div className="section-empty"><Icon size={28}/><b>{title} foundation is ready</b><p>This surface is scaffolded for the next implementation phase. Backend data isolation and security land before live data.</p></div>}</section>}
export default App;

